### ISSUE TITLE
precompiled binarie

### ISSUE THREAD

**Issue by HoerMirAuf** [sile/wstcp#5]
Are there precompiled binaries for old i386 linux, too?

**Comment by sile** [comment]
No, there aren't.
Looking at [Platform Support page](https://doc.rust-lang.org/rustc/platform-support.html),  Rust seems not support i386 linux musl build. So it's difficult to provide the precompiled binaries I think.

**Comment by HoerMirAuf** [comment]
Hallo.It wasn't any problem to install Cargo on a old Puppy-Linux i386 Distribution and compile a 32bit binarie Packed it to a ZIP as Attachment Am 08.03.2023 15:03 schrieb Takeru Ohta ***@***.***>:
No, there aren't.
Looking at Platform Support page,  Rust seems not support i386 linux musl build. So it's difficult to provide the recompiled binaries I think.

**Comment by sile** [comment]
Thank you for your information, but I didn't receive the attachment (email's attachments would be dropped by GitHub system I think).
I guess that you compiled `wstcp` using non musl target. Non musl binaries are less portable (e.g., having a dynamic link dependency to a specific version of libc). So I want to use musl build for precompiled binaries.
I tried building `i586-unknown-linux-musl` and `i686-unknown-linux-musl` contained in the following ZIP file:
- [wstcp.zip](https://github.com/sile/wstcp/files/10974856/wstcp.zip)

Could you confirm if they are executable on your platform?
