### ISSUE TITLE
Broken listening on the websocket with the latest Rust

### ISSUE THREAD

**Issue by vakabus** [sile/wstcp#6]
# What I do

```sh
# build
git clone https://github.com/sile/wstcp.git
cd wstcp
cargo update  # required, otherwise compilation fails
cargo build --release

# experiment
ncat -l 8000 &
cargo run --release -- --bind-addr 0.0.0.0:4000 --log-level debug 127.0.0.1:8000 &
sleep 10  # make sure wstcp starts
echo hello | websocat ws://127.0.0.1:4000
```

# What I observe

Nothing happens. The log ends with:

```
Aug 03 12:59:15.494 INFO Starts a WebSocket proxy server, server_addr: 127.0.0.1:8000, proxy_addr: 0.0.0.0:4000
```

# What I expect

There should be log messages about the websocket connection (log-level set to debug). Also, the word `hello` should be printed by `ncat`.

# What I believe is wrong

I think that this line does not work as expected with the newest Rust version:
https://github.com/sile/wstcp/blob/3c062b7d2f1bf53d02b8e994c6bd4464623f3444/src/server.rs#L46

The `incoming()` function should be called only once, not every time in the loop. I tried to fix change it and it seems to be working:
https://github.com/vakabus/wsvsock/commit/8fdb785328305e47db29d3a60a824d1105de11bc

However, I just had a hunch that this could be wrong. I couldn't find any mentions in documentation about it. Also, my changes are quick-and-dirty. I haven't tried to make the code clean, it's just a quick fix. I can make a PR if you want, but I think the `TcpListener` object can be stored at a better place (I tried putting it into the `ProxyServer` struct, but that leads to self-reference.)

**Comment by sile** [comment]
Thank you for creating this issue.  Your PR is very welcome!
(Just a passing thought, the codebase of `wstcp` might be a bit outdated. If I have enough time, rewriting it from scratch could be the best option. I don't have the time though...)

**Comment by vakabus** [comment]
> Thank you for creating this issue. Your PR is very welcome!

Sure, I'll submit a PR soon...

> (Just a passing thought, the codebase of wstcp might be a bit outdated. If I have enough time, rewriting it from scratch could be the best option. I don't have the time though...)

:shrug:  I guess that today, we could use the [`websocket` crate](https://docs.rs/websocket/latest/websocket/) and build a rather simple async copy loop on top of `tokio` to shove data from one socket to the other. But as long as this code works...
