### ISSUE TITLE
Published cargo version differs from source code

### ISSUE THREAD

**Issue by jacobdr** [sile/wstcp#9]
I've been having a play around and there seem to be some differences between the cargo version where I see logs like this:

```
Tries to connect the real server, client_addr: 192.168.65.1:40247, server_addr: 172.18.0.2:5432, proxy_addr: 0.0.0.0:5433
Connected to the real server, client_addr: 192.168.65.1:40247, server_addr: 172.18.0.2:5432, proxy_addr: 0.0.0.0:5433
Handshake response has been written, relay_addr: 172.18.0.3:40392, client_addr: 192.168.65.1:40247, server_addr: 172.18.0.2:5432, proxy_addr: 0.0.0.0:5433
WebSocket handshake succeeded, relay_addr: 172.18.0.3:40392, client_addr: 192.168.65.1:40247, server_addr: 172.18.0.2:5432, proxy_addr: 0.0.0.0:5433
TCP stream for WebSocket has been closed, relay_addr: 172.18.0.3:40392, client_addr: 192.168.65.1:40247, server_addr: 172.18.0.2:5432, proxy_addr: 0.0.0.0:5433
A proxy channel terminated normally, client_addr: 192.168.65.1:40247, server_addr: 172.18.0.2:5432, proxy_addr: 0.0.0.0:5433
```

and the locally built version from `master` where a lot of that context is missing:

```
[2024-04-15T21:30:18Z DEBUG wstcp::channel] Tries to connect the real server
[2024-04-15T21:30:18Z DEBUG wstcp::channel] Connected to the real server
[2024-04-15T21:30:18Z DEBUG wstcp::channel] Handshake response has been written
[2024-04-15T21:30:18Z INFO  wstcp::channel] WebSocket handshake succeeded
[2024-04-15T21:30:18Z INFO  wstcp::channel] TCP stream for WebSocket has been closed
[2024-04-15T21:30:18Z INFO  wstcp::server] A proxy channel terminated normally
```

Am I missing something here? 

Thanks for making this, cool concept

**Comment by sile** [comment]
The unpublished master branch includes the commit https://github.com/sile/wstcp/commit/0a8a41bf96a0fcb2f0c1288ec389d9aaa915862f in which the logger has been changed from `slog` to `log` (to reduce maintenance cost as my other repositories use `log`). 
This is the cause of the reported change.

I'm not sure but using [structure logging feature of log](https://docs.rs/log/latest/log/#structured-logging) could be add the additional context to log messages.
(If you are interested in implementing that, PR is welcomed.)

**Comment by jacobdr** [comment]
Thanks for the answer, makes sense. We can close this issue and maybe I'll create another one to track ^^ . There is actually one other small change I want to PR as well which is case-insensitivity of checking the `Connection: Upgrade` header, so Ill also open an issue for that so I can associate PRs to them

**Comment by sile** [comment]
👍
